# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[>](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[>](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[azure]
disabled = true

[battery]
disabled = true

[cmake]
disabled = true

[cobol]
disabled = true


[directory]
truncation_length = 4
truncation_symbol = ".../"

[git_branch]
disabled = true
format = "Git: [$symbol$branch]($style) "

[helm]
format = "Helm: [⎈ $version](bold white) "

[hostname]
ssh_only = false
format =  "@[$hostname](bold red)"
disabled = false

[kubernetes]
format = ' [$context \($namespace\)](dimmed green) '
disabled = false

[openstack]
format = "OpenStack: [$symbol$cloud(\\($project\\))]($style) "
style = "bold yellow"
symbol = "☁️ "

[terraform]
format = "[TF]($style) "

[username]
style_user = "white bold"
style_root = "black bold"
format = "user: [$user]($style) "
disabled = false
show_always = true