
auth_enabled: false

server:
  http_listen_port: 3100

distributor:
  ring:
    kvstore:
      store: "memberlist"

ingester:
  lifecycler:
    ring:
      kvstore:
        store: "memberlist"
      replication_factor: 1
    final_sleep: "0s"
  chunk_idle_period: "5m"
  chunk_retain_period: "30s"

memberlist:
  abort_if_cluster_join_fails: false

  # Expose this port on all distributor, ingester
  # and querier replicas.
  bind_port: 7946

  # You can use a headless k8s service for all distributor,
  # ingester and querier components.
  join_members:
  - "localhost:7946"

  max_join_backoff: "1m"
  max_join_retries: 10
  min_join_backoff: "1s"

schema_config:
  configs:
  - from: "2020-05-15"
    store: "boltdb-shipper"
    object_store: "s3"
    schema: "v11"
    index:
      prefix: "index_"
      period: "24h"

storage_config:
  boltdb_shipper:
    active_index_directory: "/tmp/loki/index"
    cache_location: "/tmp/loki/index_cache"
    shared_store: "s3"
  aws:
    endpoint: "172.16.102.113:9000"
    bucketnames: "logs"
    access_key_id: "tuto"
    secret_access_key: "tutojres"
    insecure: true
    s3forcepathstyle: true

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: "168h"

compactor:
  working_directory: "/tmp/data/compactor"
  shared_store: "s3"
  compaction_interval: "5m"