## Visualiser des notes de 1 à 5 via jres_hello_total

-> Métriques en live sur la datasource Thanos/Foo 

## Afficher des questions via les logs de l'app nginx/jres

Les deux s'affichent en temps réel dans un dashboard Grafana

echo "
log_format json_combined escape=json
  '{'
    '"time_local":"$time_local",'
    '"remote_addr":"$remote_addr",'
    '"remote_user":"$remote_user",'
    '"question":"$request_uri",'
    '"status": "$status",'
    '"body_bytes_sent":"$body_bytes_sent",'
    '"request_time":"$request_time",'
    '"http_referrer":"$http_referer",'
    '"http_user_agent":"$http_user_agent"'
  '}';
" | sudo tee /etc/nginx/conf.d/json-combined.conf

sudo vi /etc/nginx/sites-enabled/jres

.On ajoute `json_combined` à la directive `access_log` pour utiliser le format JSON
----
access_log /var/log/nginx/access-jres.log json_combined;
----

.On applique la nouvelle configuration
----
sudo systemctl reload nginx
----


logcli query '{app="jres"} | json | line_format "{{.question}}"'  --org-id="foo" --tail --no-labels --since=1m