config:
  snippets:
    pipelineStages:
    - cri: {}
    extraClientConfigs: |
      external_labels:
        dc: "dc-2"
        cluster: "kube-hoster"
    extraRelabelConfigs:
      - action: "labelmap"
        regex: "__meta_kubernetes_pod_label_(.+)"