apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-jres.fullname" . }}
  labels:
    {{- include "demo-jres.labels" . | nindent 4 }}
data:
  main.py: |
{{ .Files.Get "app/main.py" | indent 4 }}
