apiVersion: v1
kind: Service
metadata:
  name: "{{ include "demo-jres.fullname" . }}-mgmt"
  labels:
    {{- include "demo-jres.labels" . | nindent 4 }}
    {{- with .Values.extraLabels }}
    {{- toYaml . | nindent 4}}
    {{- end }}
    mgmt: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9090
      protocol: TCP
      name: mgmt
  selector:
    {{- include "demo-jres.selectorLabels" . | nindent 4 }}
